# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ANUBIS' do

  use_frameworks!

  pod 'Firebase/Analytics', '~> 7.10.0'
  pod 'Firebase/Database', '~> 7.10.0'
  pod 'Firebase/Crashlytics'
  pod 'GoogleMaps', '4.2.0'
  pod 'Google-Mobile-Ads-SDK', '8.3.0'

end
